### ISSUE TITLE
MALAMUTE SQA gaps

### ISSUE THREAD

**Issue by cticenhour** [idaholab/malamute#73]
## Description
MALAMUTE has gaps in SQA due to changes in templates from idaholab/moose#20971 and is otherwise missing required documents.

## Steps to Reproduce
```
cd ~/projects/malamute
make -j8
cd doc
./moosedocs.py check 
```

As of 2023/09/28, the `check` command produces the following output:

<details>
  <summary>Click to see output</summary>
  
```
--------------------------------------------------------------------------------
MOOSEAPP REPORT(S):
--------------------------------------------------------------------------------
malamute WARNING
              log_default: 0
           log_stub_files: 16
      log_duplicate_files: 0
  log_missing_description: 9
     log_missing_markdown: 0


--------------------------------------------------------------------------------
DOCUMENT REPORT(S):
--------------------------------------------------------------------------------
Documents WARNING
                                log_default: 0
          log_safety_software_determination: 0
            log_quality_level_determination: 0
          log_enterprise_architecture_entry: 0
                  log_software_quality_plan: 0
          log_configuration_management_plan: 0
                     log_software_test_plan: 0
                  log_asset_management_plan: 0
           log_verification_validation_plan: 0
    log_software_requirements_specification: 0
            log_software_design_description: 0
        log_requirements_traceablity_matrix: 0
         log_verification_validation_report: 0
                log_failure_analysis_report: 0
  log_communication_and_contact_information: 0
              log_software_coding_standards: 0
                  log_software_library_list: 0
                            log_user_manual: 1
                          log_theory_manual: 1



--------------------------------------------------------------------------------
REQUIREMENT REPORT(S):
--------------------------------------------------------------------------------
malamute WARNING
                  log_default: 0
   log_deprecated_requirement: 0
        log_deprecated_design: 0
        log_deprecated_issues: 0
        log_deprecated_detail: 0
  log_deprecated_verification: 0
    log_deprecated_validation: 0
  log_deprecated_with_details: 0
                  log_missing: 2
      log_missing_requirement: 36
           log_missing_design: 36
           log_missing_issues: 0
        log_empty_requirement: 0
             log_empty_design: 0
             log_empty_issues: 0
       log_empty_verification: 0
         log_empty_validation: 0
         log_top_level_detail: 1
           log_missing_detail: 0
             log_empty_detail: 0
        log_extra_requirement: 0
             log_extra_design: 0
             log_extra_issues: 0
        log_extra_collections: 0
       log_invalid_collection: 0
             log_issue_format: 0
             log_design_files: 0
         log_validation_files: 0
       log_verification_files: 0
                 log_testable: 0
    log_duplicate_requirement: 3
         log_duplicate_detail: 0

CRITICAL:0 ERROR:0 WARNING:105
```

</details>

## Impact
No impact to end users right now, but MALAMUTE is out-of-compliance with our SQA practices. This might be important in the future. 

---

## Checklist for closing this issue

- Documents
    - [ ] Theory manual (disabled in #107, added in #124)
    - [x] User manual (set to index index, #107)
    - [ ] Safety Software Determination (SSD)
    - [ ] Quality Level Determination (QLD)
    - [ ] Enterprise Architecture Entry
    - [x] Software Quality Plan (SQAP) (#74)
    - [ ] Configuration Management Plan
    - [ ] Asset Management Plan
    - [ ] Verification Validation Plan (VVP)
    - [x] Communication and Contact Information (CCI) (#74)
    - [x] Software Coding Standards (SCS) (#74)
- Individual Document Entries
    - Software Requirements Specifciation (SRS) (#74)
        - [x] System Purpose
        - [x] System Scope
        - [x] User Characteristics
        - [x] Assumptions and Dependencies
        - [x] Reliability
        - [x] Information Management
        - [x] Policies and Regulations
        - [x] Packaging
    - System Design Description (SDD) (#74)
        - [x] Introduction
        - [x] System Scope
        - [x] Dependencies and Limitations
        - [x] Design Stakeholders
        - [x] System Design
        - [x] System Structure
    - Requirements Traceability Matrix (RTM) (#74)
        - [x] System Purpose
        - [x] System Scope
- [x] Missing issues (#74, #107)
- [x] Missing test design files designation (some in #74)
- [x] Missing or conflicting design files (some in #74)
- [x] Duplicate requirements (#74, #107)

**Comment by cticenhour** [comment]
## Checklist for closing this issue

- Documents
    - [ ] Theory manual
    - [ ] User manual
    - [ ] Safety Software Determination (SSD)
    - [ ] Quality Level Determination (QLD)
    - [ ] Enterprise Architecture Entry
    - [ ] Software Quality Plan (SQAP)
    - [ ] Configuration Management Plan
    - [ ] Asset Management Plan
    - [ ] Verification Validation Plan (VVP)
    - [ ] Communication and Contact Information (CCI)
    - [ ] Software Coding Standards (SCS)

- Individual Document Entries
    - Software Requirements Specifciation (SRS)
        - [ ] System Purpose
        - [ ] System Scope
        - [ ] User Characteristics
        - [ ] Assumptions and Dependencies
        - [ ] Reliability
        - [ ] Information Management
        - [ ] Policies and Regulations
        - [ ] Packaging
    - System Design Description (SDD)
        - [ ] Introduction
        - [ ] System Scope
        - [ ] Dependencies and Limitations
        - [ ] Design Stakeholders
        - [ ] System Design
        - [ ] System Structure
    - Requirements Traceability Matrix (RTM)
        - [ ] System Purpose
        - [ ] System Scope

- [ ] Missing issues (7)
- [ ] Missing test design files designation (11)
- [ ] Missing or conflicting design files (5)
- [ ] Duplicate requirements (4)
